{% set name = "nlpaug" %}
{% set version = "1.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/makcedward/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: dab68723994c6b4503f20f543dad80a1a2177791520115313a80a6d1167e69a4

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - datasets >=1.8.0
    - gdown >=4.0.0
    - numpy >=1.16.2
    - pandas
    - python >={{ python_min }}
    - pytorch >=1.2.0
    - requests >=2.22.0
    - sentencepiece
    - transformers

test:
  imports:
    - nlpaug
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/makcedward/nlpaug
  license: MIT
  license_file: LICENSE
  summary: Natrual language processing data Augmentation library
  description: |
    This python library helps you with augmenting NLP for your machine learning
     projects. `Augmenter` is the basic element of augmentation while `Flow` is
     a pipeline to orchestra multi augmenter together. Nlpaug generates
     synthetic data for improving model performance without manual effort. It is
     a simple and easy-to-use and lightweight library where you can augment data
     in 3 lines of code, and features plug and play to any machine leanring
     and neural network frameworks (e.g. scikit-learn, PyTorch, TensorFlow).
     Nlpaug supports textual and audio input as well.


extra:
  recipe-maintainers:
    - thewchan
